endpoints:
  - exposed_ip: localhost
    local_bind_ip: localhost
    port: 8748
    id: 0
    replicaid: 0
    raftport: 3124
  # - exposed_ip: localhost
  #   local_bind_ip: localhost
  #   port: 8749
  #   id: 0
  #   replicaid: 1
  #   raftport: 3125
  # - exposed_ip: localhost
  #   local_bind_ip: localhost
  #   port: 8750
  #   id: 0
  #   replicaid: 2
  #   raftport: 3126
  # - exposed_ip: localhost
  #   local_bind_ip: localhost
  #   port: 8751
  #   id: 1
  #   replicaid: 0
  #   raftport: 3127
  # - exposed_ip: localhost
  #   local_bind_ip: localhost
  #   port: 8752
  #   id: 1
  #   replicaid: 1
  #   raftport: 3128
  # - exposed_ip: localhost
  #   local_bind_ip: localhost
  #   port: 8753
  #   id: 1
  #   replicaid: 2
  #   raftport: 3129