endpoints:
  - exposed_ip: 127.0.0.1
    local_bind_ip: 127.0.0.1
    deploy_host: host1
    port: 8745
    id: 0
  # - exposed_ip: 192.168.252.117
  #   local_bind_ip: 192.168.252.117
  #   deploy_host: host2
  #   port: 8745
  #   id: 1
  # - exposed_ip: 192.168.252.119
  #   local_bind_ip: 192.168.252.119
  #   deploy_host: host3
  #   port: 8745
  #   id: 2