endpoints:
  - exposed_ip: 127.0.0.1
    local_bind_ip: 127.0.0.1
    deploy_host: host1
    port: 8748
    id: 0
    replicaid: 0
    raftport: 3124
  # - exposed_ip: 192.168.252.117
  #   local_bind_ip: 192.168.252.117
  #   deploy_host: host2
  #   port: 8749
  #   id: 0
  #   replicaid: 1
  #   raftport: 3125
  # - exposed_ip: 192.168.252.119
  #   local_bind_ip: 192.168.252.119
  #   deploy_host: host3
  #   port: 8750
  #   id: 0
  #   replicaid: 2
  #   raftport: 3126
  # - exposed_ip: 192.168.252.117
  #   local_bind_ip: 192.168.252.117
  #   deploy_host: host2
  #   port: 8751
  #   id: 1
  #   replicaid: 0
  #   raftport: 3127
  # - exposed_ip: 192.168.252.115
  #   local_bind_ip: 192.168.252.115
  #   deploy_host: host1
  #   port: 8752
  #   id: 1
  #   replicaid: 1
  #   raftport: 3128
  # - exposed_ip: 192.168.252.119
  #   local_bind_ip: 192.168.252.119
  #   deploy_host: host3
  #   port: 8753
  #   id: 1
  #   replicaid: 2
  #   raftport: 3129
  # - exposed_ip: 192.168.252.119
  #   local_bind_ip: 192.168.252.119
  #   deploy_host: host3
  #   port: 2754
  #   id: 2
  #   replicaid: 0
  #   raftport: 3130
  # - exposed_ip: 192.168.252.115
  #   local_bind_ip: 192.168.252.115
  #   deploy_host: host1
  #   port: 2755
  #   id: 2
  #   replicaid: 1
  #   raftport: 3131
  # - exposed_ip: 192.168.252.117
  #   local_bind_ip: 192.168.252.117
  #   deploy_host: host2
  #   port: 2756
  #   id: 2
  #   replicaid: 2
  #   raftport: 3132