endpoints:
  - exposed_ip: 127.0.0.1
    local_bind_ip: 127.0.0.1
    deploy_host: host1
    port: 8751
    id: 0
    replicaid: 0
    raftport: 3127
  - exposed_ip: 127.0.0.1
    local_bind_ip: 127.0.0.1
    deploy_host: host1
    port: 8752
    id: 0
    replicaid: 1
    raftport: 3128
  - exposed_ip: 127.0.0.1
    local_bind_ip: 127.0.0.1
    deploy_host: host1
    port: 8753
    id: 0
    replicaid: 2
    raftport: 3129